language: go
go:
- '1.7'
env:
  global:
  - SOURCE_DIR="public"
  - BUILD_BRANCH="source"
  - DEPLOY_BRANCH="master"
before_install:
- openssl aes-256-cbc -K $encrypted_b20e39435737_key -iv $encrypted_b20e39435737_iv
  -in .travis/travis_rsa.enc -out /tmp/travis_rsa -d
install:
- go get -u -v github.com/spf13/hugo
before_script:
# - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
- go get -u -v github.com/spf13/hugo
script:
- hugo
before_deploy:
- openssl aes-256-cbc -K $encrypted_b20e39435737_key -iv $encrypted_b20e39435737_iv
  -in .travis/travis_rsa.enc -out /tmp/travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis_rsa
- ssh-add /tmp/travis_rsa
after_success:
- "./.travis/publish.sh"
